[api]
url = "https://api.openweathermap.org/data/2.5/weather?"
appid = YOUR APP ID HERE

[db]
schema = "postgres"
url = "YOUR FULL POSTGRES URL HERE"

[token]
secret = "YOUR TOKEN SECRET VALUE HERE"
timeValid = "HOW LONG YOU WANT YOUR JWT TOKEN VALID HERE"
